name: TOM CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: 'temurin'

      - name: Run Tests + ChainTest + Logging
        run: |
          mvn -B -e clean test -Dproject.root=${{ github.workspace }}

      - name: Upload ChainTest Report
        uses: actions/upload-artifact@v4
        with:
          name: chaintest-report
          path: core/reports/chaintest/

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: core/reports/logs/